# Setup
title:               Sabarish's blog
tagline:             little bit of everything.
description:         Let's build stuff.
url:                 https://sks3i.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sabarish K S
  url:               https://sks3i.github.io/
  email:             saba.rish91@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

collections:
  just_math:
    output: true
  cooking:
    output: true

# Front matter defaults for collections
defaults:
  - scope:
      path: "_just_math"
      type: just_math
    values:
      layout: post
  - scope:
      path: "_cooking"
      type: cooking
    values:
      layout: post
