# Setup
title:               Sabarish's blog
tagline:             Personal blog - AI, Robotics, and more
description:         This is my personal blog where I write about AI, Robotics, and more.
url:                 https://sks3i.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sabarish K S
  url:               https://sks3i.github.io/
  email:             sks3i@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
