title: Sabarish's blog
author: Sabarish Kuduwa Sivanath
subtitle: Random articles on Machine Learning, Robotics and more

url: "https://sks3i.github.io"
baseurl: 

footer_only_homepage: true
footer_url: "https://github.com/sks3i"
footer_text: "Activating one neuron at a time. Slow and steady"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
